version: '2'
services:
    isit-app:
        image: isit
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://isit-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=isIt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    isit-mongodb:
        extends:
            file: mongodb.yml
            service: isit-mongodb
